name: render

on:
  push:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - name: Render README.md
        run: |
          uv run python main.py

      - name: Commit and push if it changed
        run: |-
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add README.md
          timestamp=$(date -u)
          git commit -m "Re-rendered README.md (${timestamp})" || exit 0
          git push
